name: Download gno docs

on:
  workflow_dispatch: {}
  push:
    branches:
      - ci/download-docs

jobs:
  commit_docs:
    runs-on: ubuntu-latest

    steps:
      - name: checkout docs.gno.land repository
        uses: actions/checkout@v4

      - name: download latest version of gnolang/gno repository
        run: |
          wget -O /tmp/gno.zip "https://github.com/gnolang/gno/archive/refs/heads/master.zip"
          unzip -d /tmp/ /tmp/gno.zip

      - name: Import docs directory
        run: |
          cp -r /tmp/gno-master/docs ./docs

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "chore(ci): import docs/ directory from gnolang/gno@master"
          git push
