name: Deploy docs to netlify

on:
  workflow_dispatch: {}
  push:
    branches:
      - ci/netlify


jobs:
  deploy-netlify:
    name: deploy-to-netlify
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: read
    steps:
    - uses: actions/checkout@v4

    - name: Deploy to netlify
      uses: netlify/actions/cli@master
      with:
        args: deploy --site albttx-gno-docs --prod
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
